### ISSUE TITLE
Black background on linux TTY

### ISSUE THREAD

**Issue by TheArcaneBrony** [nickvdyck/nyancat.cs#10]
Background is black on virtual terminals.
![image](https://user-images.githubusercontent.com/13570458/126783653-34841e52-5f1a-4b93-ad69-f5a35bf4d1d0.png)

**Comment by vandycknick** [comment]
Hey, thanks for flagging this. I would love to take a look at it but will need a bit more information before I can do so. 

__What version are you currently running?__

```
nyancat --version
```

__Can you tell me what Linux distro you are currently using?__

```
uname -a
cat /etc/*release
stty -a
echo $TERM
echo $COLOR_TERM
```

Feel free to share whatever you feel most comfortable with.

__What colour scheme are you using?__

**Comment by TheArcaneBrony** [comment]
`nyancat --version` returns that it's version 1.5.0

Linux distro: Arch linux, last updated in the last 2 days
Here's the output of all those commands:
```
Linux arch-amd 5.13.6-arch1-1 #1 SMP PREEMPT Thu, 29 Jul 2021 00:21:06 +0000 x86_64 GNU/Linux
Arch Linux release
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
speed 38400 baud; rows 67; columns 240; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>;
eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R;
werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 hupcl -cstopb cread -clocal -crtscts
-ignbrk brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff
-iuclc -ixany imaxbel iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt
echoctl echoke -flusho -extproc
linux```

**Comment by TheArcaneBrony** [comment]
Can also reproduce on ubuntu 21.04, on a tty. In this case the background is light blue, the tail color is orange, yellow and green, and the cat is black...

**Comment by vandycknick** [comment]
Gotcha, I understand now what you meant with `on a Linux TTY`. I have also been able to reproduce this from my end now. Not sure yet how to fix it though, will need to figure out how to best tweak the colour palette and the colour detection. I have noticed a few other TTY rendering libraries also having issues in this mode. 

If you have any ideas on how to best approach this, please do let me know 😄 .

**Comment by vandycknick** [comment]
A Linux TTY only has 8 colours available, hence why stuff looks rather weird. I added https://github.com/vandycknick/nyancat.cs/commit/2096927e7ee1265d8a51ce9230bbfa76670a2d26 which improves the colour detection and makes better use of the 8 available colours. The background will now be blue, but the cat remains fully black because I ran out of colours.

**Comment by TheArcaneBrony** [comment]
After doing some research on that apparently it's possible to get a 16-color mode.
That aside, fbterm (framebuffer tty) offers 256color mode. I should look into how it behaves under that setup.
