### ISSUE TITLE
Help for the "frames" argument needs correcting

### ISSUE THREAD

**Issue by f3** [nickvdyck/nyancat.cs#9]
The help message for the `--frames` argument is shown incorrectly (at least for Windows).  Currently, it reads
```
  -f, --frames=VALUE         Display the requested number of frames, then quit.
```
In a Windows command prompt, it chokes on the "=" bit:
```bash
[C:\code\github\nickvdyck\nyancat.cs]
$ nyancat --frames=10
Unkown argument: --frames=10

Try `nyancat --help' for more information.

[C:\code\github\nickvdyck\nyancat.cs]
$
```
Running it without the "=" (`nyancat --frames 10`) works perfectly

**Comment by vandycknick** [comment]
Thanks for flagging :raised_hands: , fixed this in f4d0ae9393f98f3e35da968c261c5c43e62a00d0 which went out in v1.5.0.
